### ISSUE TITLE
Cannot run on my android emulator

### ISSUE THREAD

**Issue by louicoder** [Albystein/React-Native-Layouts#1]
The application seems not to run on my android emulator. I went ahead and tried this on a physically connected device and still got the same issue. Please refer to screenshot below.

![image](https://user-images.githubusercontent.com/32771081/57914052-957dfc00-7896-11e9-9e26-6c23064e5da4.png)

**Comment by atemaguer** [comment]
the error is not verbose enough.
Is it still not working?

**Comment by atemaguer** [comment]
the issue maybe with your devices not being configured to use the right port 8081. yours seems to be using port 5037

**Comment by atemaguer** [comment]
run the following command.

adb -s <device_name> reverse tcp:8081 tcp:8081

**Comment by louicoder** [comment]
Cool, I will try that. Have you added any updates yet @Albystein

**Comment by louicoder** [comment]
You might wanna contribute to our application we are building in react-native. Feel free to let me know so I can add you. Good work :+1:

**Comment by atemaguer** [comment]
sure. let me check it out.

And yes, I just added the Vacation home app this evening. it is more
responsible and better organised. I am going to organize the others as well
and make them a bit responsible where necessary.

**Comment by louicoder** [comment]
This issue is to due with permissions though, not reversing the port as indicated. 
For more info checkout this github issue. [Here](https://github.com/facebook/react-native/issues/17197#issuecomment-398829408)

**Comment by atemaguer** [comment]
so it's more of the file grades.bat not having the permission to execute.
explains the permission denied errors. thanks for finding it out.
